# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']
    image_uploader:
        class: App\Service\FileUploader
        arguments: ['%images_directory%']
    repo.promotions:
        class: Doctrine\ORM\EntityRepository
        factory: ['@doctrine.orm.entity_manager', getRepository]
        arguments:
            - \App\Entity\Promotion
    promotion_manager:
        class: App\Service\PromotionManager
        arguments: ['@repo.promotions']
    price_calculator:
        class: App\Service\PriceCalculator
        arguments: ['@promotion_manager']
        public : true
    store_manager:
        class: App\Service\StoreManager